### ISSUE TITLE
Bot spamming on group messages

### ISSUE THREAD

**Issue by thesandstorm15** [djohsson/Lastgram#22]
Hey there =)
Sorry for annoying you again 
I just updated the bot to the newest release, and it works fine with scrobbles now, but its spamming when receiving any group messages with "Ops, something went wrong"

`
lastgram_1  |    at Lastgram.Commands.CommandHandler.ExecuteCommandAsync(Message message, Func`3 responseFunc) in /src/Lastgram/Commands/CommandHandler.cs:line 23
lastgram_1  |    at Lastgram.Bot.ExecuteCommandAsync(MessageEventArgs eventArgs) in /src/Lastgram/Bot.cs:line 62
lastgram_1  | System.NullReferenceException: Object reference not set to an instance of an object.
lastgram_1  |    at Lastgram.Commands.CommandHandler.TryParseCommandType(Message message, Type& type) in /src/Lastgram/Commands/CommandHandler.cs:line 73
lastgram_1  |    at Lastgram.Commands.CommandHandler.ExecuteCommandAsync(Message message, Func`3 responseFunc) in /src/Lastgram/Commands/CommandHandler.cs:line 23
lastgram_1  |    at Lastgram.Bot.ExecuteCommandAsync(MessageEventArgs eventArgs) in /src/Lastgram/Bot.cs:line 62
`

This is what i get on console.

**Comment by djohsson** [comment]
I can see the issue in the code. Just confused about it responding to every message... It should only be able to read messages that are the specified commands. Works fine in my group chat

**Comment by djohsson** [comment]
Ah, I think you have disabled Group Privacy for the bot. It should look like this: 
![image](https://user-images.githubusercontent.com/5834595/120102104-c5c92800-c149-11eb-8696-5cd776958ecf.png)


See: https://stackoverflow.com/questions/50204633/allow-bot-to-access-telegram-group-messages

Enable it, kick the bot, and then invite it again. Should solve it. I will fix the issue in the code later today

**Comment by djohsson** [comment]
Should be fixed with https://github.com/djohsson/Lastgram/commit/beb6121612b02f041a5b270f756b9bd7826d76b0
